Feat/actions
ungdev/UA-front pull request #172
Opened 2021-09-26 17:59 UTC by Azerty6

2021-09-27 22:23 UTC, AlbanSdl commented
Hey !
Juste pour la précision: l'api utilise les actions sous la forme 
```ts
const link = `${env.front.website}/?action=${ActionFeedback.PASSWORD_RESET}&state=${user.resetToken}`
```
Autrement dit, les deux params de la query sont `action` et **`state`**.
Aussi, contrairement à ce qui était écrit sur la carte, la troisième action s'appelle `validate` :wink:

Bien sûr, si vous n'aimez pas dites le moi et on peut modifier ces valeurs :)
(Liens vers les defs: [`pwd-reset`](https://github.com/ungdev/UA-api/blob/dev/src/services/email/serializer.ts#L185), [`validate`](https://github.com/ungdev/UA-api/blob/dev/src/services/email/serializer.ts#L132), [`ActionFeedback`](https://github.com/ungdev/UA-api/blob/dev/src/types.ts#L13))

2021-09-29 18:24 UTC, Saperlu requested changes

2021-09-29 18:24 UTC, Saperlu commented on src/components/Wrapper.jsx
> +        dispatch(saveToken(res.data.token));
Normalement, après l'action on est login mais c'est pas le cas quand je test en local, faut revoir ça

2021-09-29 18:24 UTC, Saperlu commented on src/components/Wrapper.jsx
> +        <Navbar isLoggedIn={isLoggedIn} action={query.action} value={query.value} />
Tu passes 2 props pour la même feature, je trouve ça plus propre de tout mettre dans un objet action

2021-09-29 19:00 UTC, AlbanSdl commented on src/components/Wrapper.jsx
> +        <Navbar isLoggedIn={isLoggedIn} action={query.action} value={query.value} />
Je reprécise juste mon commentaire: il y a une coquille dans la doc, pour unifier les actions, tous les codes qui sont renvoyés avec sont renvoyés dans `state` et non dans `code` ou `value` ou quoi que ce soit d'autre ^^
Je corrigerai ça dans la doc :)

2021-09-30 14:21 UTC, Saperlu requested changes

2021-09-30 14:21 UTC, Saperlu commented on src/components/Wrapper.jsx
> +        dispatch({
Un seul dispatch qui renvoit vers login.js, c'est mieux

2021-09-30 14:21 UTC, Saperlu commented on src/components/Wrapper.jsx
> +    }
```suggestion
    }
    // 3 actions possible : 
    //  - oauth
    //  - validate
    //  - pwd-reset
```

2021-10-01 12:58 UTC, Saperlu reviewed
Y'a des souci sur le reset, je me prend des erreurs 400 en testant, je te laisse debug

2021-10-01 12:58 UTC, Saperlu commented on src/components/ResetModal.jsx
> +import { API } from '../utils/api';
```suggestion
import { API } from '../utils/api';
import { toast } from 'react-toastify';
```

2021-10-01 12:58 UTC, Saperlu commented on src/components/ResetModal.jsx
> +          }
```suggestion
          replace(pathname);
```

2021-10-05 07:25 UTC, Saperlu approved these changes

2021-10-05 07:27 UTC, merged