Added a list to all the things people should bring to the event
ungdev/UA-front pull request #206
Opened 2021-11-23 19:33 UTC by Azerty6

2021-11-23 22:59 UTC, AlbanSdl requested changes

2021-11-23 22:59 UTC, AlbanSdl commented on src/pages/dashboard/account.jsx
> +
Relis ton commentaire 😂

2021-11-23 23:12 UTC, AlbanSdl commented on src/pages/dashboard/account.jsx
> -        <div>
Pourquoi pas `user.compumsaCode && (<div>...</div>)` ?

2021-11-24 09:24 UTC, Azerty6 commented on src/pages/dashboard/account.jsx
> -        <div>
Parce que c'était comme ça avant ¯\_(ツ)_/¯. Je me suis posé la même question aussi, mais je me suis dit que ça servait à rien de modif si c'était pas nécessaire. Mais on peut changer si tu veux

2021-11-24 09:24 UTC, Azerty6 commented on src/pages/dashboard/account.jsx
> +
#OnNaRienVu

2021-11-24 11:09 UTC, AlbanSdl commented on src/pages/dashboard/account.jsx
> -        <div>
C'est juste que l'opérateur ternaire est un peu lourd en terme de syntaxe (genre ça force à mettre un else avec `''`)

2021-11-24 11:10 UTC, AlbanSdl approved these changes

2021-11-24 13:56 UTC, merged